import { ReactComponent as PlayIconIm } from "../includes/icons/play.svg";
import { ReactComponent as DownIconIm } from "../includes/icons/down.svg";
import { ReactComponent as TrashIconIm } from "../includes/icons/trash.svg";
import { ReactComponent as DropIconIm } from "../includes/icons/drop.svg";
import { ReactComponent as LinkedinM } from "../includes/icons/linkedin.svg";
import { ReactComponent as GithubM } from "../includes/icons/github.svg";
import { ReactComponent as GithubAltM } from "../includes/icons/githubAlt.svg";
export const PlayIcon = PlayIconIm;
export const DownIcon = DownIconIm;
export const TrashIcon = TrashIconIm;
export const DropIcon = DropIconIm;
export const LinkedinIcon = LinkedinM;
export const GithubIcon = GithubM;
export const GithubAltIcon = GithubAltM;
